import Head from "next/head";
import * as styles from "../styles/Home.module.css";
import { SiSpotify } from "react-icons/si";
import useSWR from "swr";

export default function Home() {
  const fetcher = (url) => fetch(url).then((r) => r.json());
  const { data } = useSWR("/api/spotify", fetcher);

  console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Spotify Connection using Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Spotify Connection using <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Display Spotify {"Currently Playing"} Activity From It{"'"}s Official
          API.
        </p>

        <div className={styles.grid}>
          <h2 className={styles.card__title}>Online Status:</h2>
          <a
            href={
              data?.isPlaying
                ? data.songUrl
                : "https://open.spotify.com/user/31mfhvof7jt4iunmo5sbs7xk3nye?si=62f0a47200fb49fb"
            }
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <div className={styles.box}>
              {data?.isPlaying ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img
                  className={styles.image}
                  src={data?.albumImageUrl}
                  alt={data?.album}
                  width="64"
                />
              ) : (
                <SiSpotify size={64} color={"#1db954"} />
              )}
            </div>

            <div className={styles.info}>
              <h2>{data?.isPlaying ? data.title : "Currently offline"}</h2>
              <p>{data?.isPlaying ? data.artist : "Spotify"}</p>
            </div>
          </a>

          <h2 className={styles.card__title}>Offline Status (example):</h2>
          <a className={styles.card}>
            <div className={styles.box}>
              <SiSpotify size={64} color={"#1db954"} />
            </div>

            <div className={styles.info}>
              <h2>{"Currently offline"}</h2>
              <p>{"Spotify"}</p>
            </div>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/ilhambara"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made in 🚀 by <b>@ilhambara</b>
        </a>
      </footer>
    </div>
  );
}
